apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kubernetesVersion: v1.28.15
networking:
  podSubnet: 10.244.0.0/16
imageRepository: 6e4mx6zwaaozht-k8s.xuanyuan.run
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
nodeRegistration:
  criSocket: unix:///run/containerd/containerd.sock
