apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
- deployment.yaml
- service.yaml
- pvc.yaml
- servicemonitor.yaml
- hpa.yaml
- ingress.yaml
- configmap.yaml

commonLabels:
  app: qwen-vllm
  managed-by: kustomize

images:
- name: qwen-vllm
  newTag: latest
